-- Nurture Schema
create table if not exists sequence_templates (id uuid primary key default gen_random_uuid(), name text not null, steps jsonb not null default '[]', active boolean default true);
create table if not exists sequence_enrolments (id uuid primary key default gen_random_uuid(), lead_id uuid references leads(id) on delete cascade, campaign_id uuid, current_step integer default 0, status text default 'active', enrolled_at timestamptz default now(), next_step_at timestamptz, paused_reason text);
create table if not exists branching_rules (id uuid primary key default gen_random_uuid(), campaign_id uuid, priority integer default 1, trigger_event text not null, action text not null, action_params jsonb, active boolean default true);
create table if not exists nurture_tracks (id uuid primary key default gen_random_uuid(), name text not null, track_type text not null, cadence_days integer default 30, steps jsonb not null default '[]', active boolean default true);
create table if not exists nurture_enrolments (id uuid primary key default gen_random_uuid(), lead_id uuid references leads(id) on delete cascade, track_id uuid references nurture_tracks(id), status text default 'active', current_step integer default 0, next_touch_at timestamptz);
create table if not exists trigger_events (id uuid primary key default gen_random_uuid(), lead_id uuid references leads(id), event_type text not null, action_taken text, fired_at timestamptz default now());
insert into nurture_tracks (name, track_type, cadence_days, steps) values ('Warm nurture','warm_nurture',30,'[]'),('Re-engagement','re_engagement',90,'[]'),('Champion track','champion',60,'[]') on conflict do nothing;
insert into branching_rules (campaign_id,priority,trigger_event,action,action_params) values (null,1,'replied_positive','assign_to_rep','{"pause_sequence":true}'),(null,2,'replied_negative','remove','{"reason":"negative"}'),(null,3,'clicked','fast_track','{"skip_to_step":4}'),(null,4,'no_open_3_days','send_variant','{"variant":"B"}'),(null,5,'replied_neutral','move_to_nurture','{"track_type":"warm_nurture"}'),(null,6,'sequence_completed','move_to_nurture','{"track_type":"warm_nurture"}') on conflict do nothing;
